export const tags = [
  "Technology",
  "Fashion",
  "Food",
  "Travel",
  "Lifestyle",
  "Health and Fitness",
  "Beauty",
  "Home Decor",
  "DIY (Do-It-Yourself)",
  "Parenting",
  "Personal Development",
  "Photography",
  "Finance",
  "Gaming",
  "Sports",
  "Entertainment",
  "Books",
  "Music",
  "Sustainability",
  "Product Reviews",
];

export const metaKeywords = [
  "Fashion",
  "Style",
  "Clothing",
  "Accessories",
  "Grooming",
  "Fashion Trends",
  "Fashion Tips",
  "Fashion Inspiration",
  "Street Style",
  "Formalwear",
  "Casualwear",
  "Footwear",
  "Bloggers",
  "Influencers",
  "Fashion Brands",
  "Guide",
  "Advice",
  "News",
  "Ideas",
  "Updates",
];
